services:
  postgresql:
    image: postgres:17
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=keycloak
    volumes:
      - "./postgresql_data:/var/lib/postgresql/data"
    networks:
      keycloak:

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    restart: always
    command: start
    depends_on:
      - postgresql
    environment:
      - KC_FEATURES=hostname:v2
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_PROXY_TRUSTED_ADDRESSES=192.168.20.50,100.64.0.15
      - KC_HOSTNAME=https://keycloak.simenmo.com
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    networks:
      proxy:
      keycloak:
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard-home.loadbalancer.server.port=8080
networks:
  proxy:
    external: true
  keycloak:
