FROM ghcr.io/secureblue/securecore-main-hardened:latest

# Copy sshd config over
COPY resources/system-configs/sshd_config /etc/ssh/

# install qemu ga
RUN dnf -y install qemu-guest-agent && dnf clean all

# install onepassword cli
RUN rpm --import https://downloads.1password.com/linux/keys/1password.asc
RUN sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'

RUN dnf check-update -y 1password-cli && dnf -y install 1password-cli

# install docker
RUN curl --output-dir "/etc/yum.repos.d" --remote-name https://download.docker.com/linux/fedora/docker-ce.repo

RUN dnf -y remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-selinux docker-engine-selinux docker-engine moby-engine containerd runc docker-cli
RUN dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

RUN systemctl enable docker

# copy docker compose and env
COPY resources/komodo/mongo.compose.yaml /etc/containers/docker/komodo/
COPY resources/komodo/compose.env /etc/containers/docker/komodo/

# copy bootstrap.sh
COPY komodo-core/bootstrap.sh /etc/

# copy compose systemd unit
COPY komodo-core/komodo-docker-compose.service /usr/lib/systemd/system/

# copy container policy
COPY resources/system-configs/policy.json /etc/containers/