when:
  - event: push
  - path:
      include:
        - "images/**"

variables:
  - &registry forgejo.simenmo.com

steps:
  build-komodo-core:
    image: woodpeckerci/plugin-kaniko
    pull: true
    settings:
      repo: ${CI_REPO_NAME}/komodo-core
      registry: *registry
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: images/komodo-core/containerfile
      context: "images/"
      tags:
        - latest
      when:
        evaluate: 'CI_COMMIT_MESSAGE contains "komodo-core" || CI_PIPELINE_FILES contains "images/komodo-core/"'
