steps:
  build-komodo-core:
    when:
      event: push
      path:
        include:
          - "images/komodo-core/**"
    image: woodpeckerci/plugin-kaniko
    pull: true
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: images/komodo-core/containerfile
      context: "images/"

      destinations:
        - forgejo.simenmo.com/simen/homelab/komodo-core:latest
