steps:
  build-komodo-core:
    when:
      - event: push
        path:
          include: ["images/komodo-core/**", "images/resources/**"]
      - event: cron
        cron: nightly_build
      - event: manual

    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo:
        - forgejo.simenmo.com/simen64/homelab/komodo-core
        - ghcr.io/simen64/homelab/komodo-core
      logins:
        - registry: https://forgejo.simenmo.com
          repo: forgejo.simenmo.com/simen64/homelab/komodo-core
          username:
            from_secret: registry_username
          password:
            from_secret: forgejo_registry_password
        - registry: https://ghcr.io
          repo: ghcr.io/simen64/homelab/komodo-core
          username:
            from_secret: registry_username
          password:
            from_secret: ghcr_registry_password
      dry-run: false
      platforms: linux/amd64
      tag: latest
      dockerfile: images/komodo-core/containerfile
      context: "images/"

  build-komodo-agent:
    when:
      - event: push
        path:
          include: ["images/komodo-agent/**", "images/resources/**"]
      - event: cron
        cron: nightly_build

    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo:
        - forgejo.simenmo.com/simen64/homelab/komodo-agent
        - ghcr.io/simen64/homelab/komodo-agent
      logins:
        - registry: https://forgejo.simenmo.com
          repo: forgejo.simenmo.com/simen64/homelab/komodo-agent
          username:
            from_secret: registry_username
          password:
            from_secret: forgejo_registry_password
        - registry: https://ghcr.io
          repo: ghcr.io/simen64/homelab/komodo-agent
          username:
            from_secret: registry_username
          password:
            from_secret: ghcr_registry_password
      dry-run: false
      platforms: linux/amd64
      tag: latest
      dockerfile: images/komodo-agent/containerfile
      context: "images/"

  build-komodo-agent-gpu:
    when:
      - event: push
        path:
          include: ["images/komodo-agent/**", "images/resources/**"]
      - event: cron
        cron: nightly_build

    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo:
        - forgejo.simenmo.com/simen64/homelab/komodo-agent-gpu
        - ghcr.io/simen64/homelab/komodo-agent-gpu
      logins:
        - registry: https://forgejo.simenmo.com
          repo: forgejo.simenmo.com/simen64/homelab/komodo-agent-gpu
          username:
            from_secret: registry_username
          password:
            from_secret: forgejo_registry_password
        - registry: https://ghcr.io
          repo: ghcr.io/simen64/homelab/komodo-agent-gpu
          username:
            from_secret: registry_username
          password:
            from_secret: ghcr_registry_password
      dry-run: false
      platforms: linux/amd64
      tag: latest
      dockerfile: images/komodo-agent/containerfile-nvidia
      context: "images/"
