when:
  - event: cron
    cron: renovate
  - event: manual

steps:
  renovate:
    image: renovate/renovate:latest
    pull: true
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ENDPOINT: https://forgejo.simenmo.com/api/v1/
      RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
      LOG_LEVEL: debug
      RENOVATE_TOKEN:
        from_secret: renovate_token
    commands:
      - renovate ${CI_REPO_OWNER}/${CI_REPO_NAME}
