services:
  traefik:
    image: traefik:v3.5
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/:/var/traefik/certs/:rw
    networks:
      - proxy

networks:
  proxy:
    name: proxy